/**
 * Static location data for preferences typeahead.
 * ~10 major countries; states/regions per country; major cities optional.
 */

export const COUNTRIES = [
  { code: 'US', name: 'United States' },
  { code: 'UK', name: 'United Kingdom' },
  { code: 'IN', name: 'India' },
  { code: 'CA', name: 'Canada' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'AU', name: 'Australia' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'SG', name: 'Singapore' },
  { code: 'IE', name: 'Ireland' },
] as const;

export const COUNTRY_NAMES = COUNTRIES.map((c) => c.name);

/** States/regions by country (name used in UI and matching). */
export const STATES_BY_COUNTRY: Record<string, string[]> = {
  'United States': [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'District of Columbia',
  ],
  'United Kingdom': ['England', 'Scotland', 'Wales', 'Northern Ireland'],
  India: [
    'Andhra Pradesh',
    'Karnataka',
    'Maharashtra',
    'Tamil Nadu',
    'Telangana',
    'Delhi',
    'Uttar Pradesh',
    'West Bengal',
    'Gujarat',
    'Rajasthan',
    'Kerala',
    'Punjab',
    'Haryana',
    'Madhya Pradesh',
    'Bihar',
    'Odisha',
    'Assam',
    'Jharkhand',
    'Chhattisgarh',
  ],
  Canada: [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Nova Scotia',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
  ],
  Germany: [
    'Baden-Württemberg',
    'Bavaria',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hesse',
    'Lower Saxony',
    'North Rhine-Westphalia',
    'Rhineland-Palatinate',
    'Saarland',
    'Saxony',
    'Saxony-Anhalt',
    'Schleswig-Holstein',
    'Thuringia',
  ],
  France: [
    'Île-de-France',
    'Auvergne-Rhône-Alpes',
    "Provence-Alpes-Côte d'Azur",
    'Occitanie',
    'Nouvelle-Aquitaine',
    'Hauts-de-France',
    'Grand Est',
    'Brittany',
    'Normandy',
    'Pays de la Loire',
  ],
  Australia: [
    'New South Wales',
    'Victoria',
    'Queensland',
    'Western Australia',
    'South Australia',
    'Tasmania',
    'Northern Territory',
    'Australian Capital Territory',
  ],
  Netherlands: [
    'North Holland',
    'South Holland',
    'Utrecht',
    'North Brabant',
    'Gelderland',
    'Others',
  ],
  Singapore: [],
  Ireland: ['Leinster', 'Munster', 'Connacht', 'Ulster'],
};

export function getStatesForCountry(countryName: string): string[] {
  return STATES_BY_COUNTRY[countryName] ?? [];
}
